import { subDays, format } from 'date-fns';
import type { User, Alert, Mission, Robot, Bin, WarehouseKPIs, AccuracyDataPoint } from '../types';

// ─── Mock Users ──────────────────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: 'user-001',
    email: 'admin@wareops.dev',
    display_name: 'Alex Rivera',
    role: 'ENTERPRISE_ADMIN',
    org_id: 'org-001',
    warehouse_ids: ['wh-001', 'wh-002', 'wh-003'],
    permissions: ['*:*'],
    status: 'ACTIVE',
    mfa_enabled: true,
    last_login_at: new Date().toISOString(),
  },
  {
    id: 'user-002',
    email: 'manager@wareops.dev',
    display_name: 'Sarah Chen',
    role: 'WAREHOUSE_MANAGER',
    org_id: 'org-001',
    warehouse_ids: ['wh-001', 'wh-002'],
    permissions: ['reports:read', 'analytics:read', 'settings:write', 'users:read'],
    status: 'ACTIVE',
    mfa_enabled: true,
    last_login_at: new Date().toISOString(),
  },
  {
    id: 'user-003',
    email: 'supervisor@wareops.dev',
    display_name: 'Marcus Johnson',
    role: 'WAREHOUSE_SUPERVISOR',
    org_id: 'org-001',
    warehouse_ids: ['wh-001'],
    permissions: ['alerts:write', 'missions:write', 'team:read', 'robots:read'],
    status: 'ACTIVE',
    mfa_enabled: false,
    last_login_at: new Date().toISOString(),
  },
  {
    id: 'user-004',
    email: 'operator@wareops.dev',
    display_name: 'Priya Patel',
    role: 'WAREHOUSE_OPERATOR',
    org_id: 'org-001',
    warehouse_ids: ['wh-001'],
    permissions: ['inventory:read', 'alerts:create', 'observations:write'],
    status: 'ACTIVE',
    mfa_enabled: false,
    last_login_at: new Date().toISOString(),
  },
  {
    id: 'user-005',
    email: 'operator2@wareops.dev',
    display_name: 'James Okafor',
    role: 'WAREHOUSE_OPERATOR',
    org_id: 'org-001',
    warehouse_ids: ['wh-001'],
    permissions: ['inventory:read', 'alerts:create', 'observations:write'],
    status: 'ACTIVE',
    mfa_enabled: false,
    last_login_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
];

// ─── Mock Alerts ─────────────────────────────────────────────────────────────
export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    type: 'MISPLACED',
    severity: 'CRITICAL',
    status: 'OPEN',
    warehouse_id: 'wh-001',
    zone_id: 'zone-A',
    bin_id: 'bin-12',
    bin_code: 'A1-R2-S3-B1',
    expected_sku: 'SKU-ELEC-001',
    observed_sku: 'SKU-FURN-002',
    title: 'Critical SKU Mismatch — High-Velocity Bin',
    description: 'Intel Core i9 Processor expected but ergonomic chair SKU found. Immediate verification required.',
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    id: 'alert-002',
    type: 'MISSING',
    severity: 'HIGH',
    status: 'ACKNOWLEDGED',
    warehouse_id: 'wh-001',
    zone_id: 'zone-B',
    bin_id: 'bin-28',
    bin_code: 'B2-R1-S4-B2',
    expected_sku: 'SKU-ELEC-002',
    title: 'Product Missing from Bin',
    description: 'Samsung 4K Monitor expected but bin appears empty. Possible theft or misfile.',
    assigned_to: 'user-004',
    created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    acknowledged_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: 'alert-003',
    type: 'ROBOT_OFFLINE',
    severity: 'HIGH',
    status: 'OPEN',
    warehouse_id: 'wh-001',
    title: 'Robot WR-003 Unresponsive',
    description: 'Robot WR-003 has not sent a heartbeat in 12 minutes. Last known position: Zone C, Aisle 3.',
    created_at: new Date(Date.now() - 1000 * 60 * 32).toISOString(),
  },
  {
    id: 'alert-004',
    type: 'EXTRA',
    severity: 'MEDIUM',
    status: 'OPEN',
    warehouse_id: 'wh-001',
    zone_id: 'zone-A',
    bin_id: 'bin-45',
    bin_code: 'A3-R4-S1-B1',
    observed_sku: 'SKU-BOOK-001',
    title: 'Unidentified Item in Bin',
    description: 'Item found in bin that has no record in WMS. Possibly misrouted from inbound dock.',
    created_at: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
  },
  {
    id: 'alert-005',
    type: 'DAMAGED',
    severity: 'MEDIUM',
    status: 'ACKNOWLEDGED',
    warehouse_id: 'wh-001',
    zone_id: 'zone-C',
    bin_id: 'bin-67',
    bin_code: 'C1-R2-S2-B2',
    expected_sku: 'SKU-FURN-001',
    title: 'Damaged Product Detected',
    description: 'Camera footage shows packaging damage on ergonomic chair SKU. QC hold recommended.',
    assigned_to: 'user-003',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString(),
    acknowledged_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
  },
  {
    id: 'alert-006',
    type: 'MISPLACED',
    severity: 'LOW',
    status: 'RESOLVED',
    warehouse_id: 'wh-001',
    bin_code: 'A2-R3-S2-B1',
    expected_sku: 'SKU-BOOK-001',
    observed_sku: 'SKU-BOOK-002',
    title: 'Minor SKU Variant Mismatch',
    description: 'Wrong edition of book found. Same product family, different variant.',
    resolution_notes: 'Operator confirmed same product, updated WMS mapping.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'alert-007',
    type: 'MISSING',
    severity: 'CRITICAL',
    status: 'OPEN',
    warehouse_id: 'wh-001',
    zone_id: 'zone-B',
    bin_code: 'B1-R1-S1-B1',
    expected_sku: 'SKU-ELEC-001',
    title: 'High-Value Item Missing — Zone B Priority',
    description: 'Entire bin contents of high-value electronics appear missing. Security alert triggered.',
    created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
  {
    id: 'alert-008',
    type: 'MANUAL',
    severity: 'LOW',
    status: 'OPEN',
    warehouse_id: 'wh-001',
    zone_id: 'zone-A',
    bin_code: 'A1-R1-S2-B2',
    title: 'Operator Reported: Label Damaged',
    description: 'Barcode label on bin is damaged and unreadable. Physical replacement needed.',
    assigned_to: 'user-005',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'alert-009',
    type: 'EXTRA',
    severity: 'MEDIUM',
    status: 'DISMISSED',
    warehouse_id: 'wh-001',
    bin_code: 'C3-R2-S3-B1',
    observed_sku: 'SKU-FURN-002',
    title: 'Overflow Stock — Non-Allocated Bin',
    description: 'Standing desk found in unallocated overflow zone. Rerouting order placed.',
    resolution_notes: 'Dismissed: overflow stock correctly placed by logistics team per WO-4421.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 'alert-010',
    type: 'ROBOT_OFFLINE',
    severity: 'HIGH',
    status: 'RESOLVED',
    warehouse_id: 'wh-001',
    title: 'Robot WR-001 Connectivity Lost — Resolved',
    description: 'Robot lost WiFi connection in Zone A dead-spot. Connection restored after relay adjustment.',
    resolution_notes: 'WiFi relay repositioned. Signal strength improved to -68dBm.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    resolved_at: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
  },
];

// ─── Mock Missions ────────────────────────────────────────────────────────────
export const MOCK_MISSIONS: Mission[] = [
  {
    id: 'mission-001',
    name: 'Zone A Full Audit',
    warehouse_id: 'wh-001',
    robot_id: 'robot-001',
    robot_name: 'WR-001 Argus',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    progress_percent: 68,
    bins_scanned: 163,
    bins_total: 240,
    started_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    eta_minutes: 19,
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
  {
    id: 'mission-002',
    name: 'Zone B Spot Check',
    warehouse_id: 'wh-001',
    robot_id: 'robot-002',
    robot_name: 'WR-002 Helios',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    progress_percent: 31,
    bins_scanned: 47,
    bins_total: 150,
    started_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    eta_minutes: 38,
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'mission-003',
    name: 'Critical SKU Verification',
    warehouse_id: 'wh-001',
    status: 'SCHEDULED',
    priority: 'CRITICAL',
    progress_percent: 0,
    bins_scanned: 0,
    bins_total: 45,
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'mission-004',
    name: 'Zone C Nightly Cycle Count',
    warehouse_id: 'wh-001',
    robot_id: 'robot-001',
    robot_name: 'WR-001 Argus',
    status: 'COMPLETED',
    priority: 'LOW',
    progress_percent: 100,
    bins_scanned: 320,
    bins_total: 320,
    started_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    completed_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(),
  },
  {
    id: 'mission-005',
    name: 'Inbound Receiving Scan',
    warehouse_id: 'wh-001',
    status: 'SCHEDULED',
    priority: 'HIGH',
    progress_percent: 0,
    bins_scanned: 0,
    bins_total: 80,
    created_at: new Date().toISOString(),
  },
];

// ─── Mock Robots ─────────────────────────────────────────────────────────────
export const MOCK_ROBOTS: Robot[] = [
  {
    id: 'robot-001',
    name: 'WR-001 Argus',
    serial_number: 'WR2024-001-ARG',
    warehouse_id: 'wh-001',
    status: 'ONLINE',
    battery_percent: 78,
    coord_x: 12.4,
    coord_y: 8.7,
    current_mission_id: 'mission-001',
    last_heartbeat_at: new Date(Date.now() - 1000 * 8).toISOString(),
  },
  {
    id: 'robot-002',
    name: 'WR-002 Helios',
    serial_number: 'WR2024-002-HEL',
    warehouse_id: 'wh-001',
    status: 'ONLINE',
    battery_percent: 54,
    coord_x: 24.1,
    coord_y: 16.2,
    current_mission_id: 'mission-002',
    last_heartbeat_at: new Date(Date.now() - 1000 * 5).toISOString(),
  },
  {
    id: 'robot-003',
    name: 'WR-003 Titan',
    serial_number: 'WR2023-003-TIT',
    warehouse_id: 'wh-001',
    status: 'ERROR',
    battery_percent: 23,
    coord_x: 36.8,
    coord_y: 4.1,
    last_heartbeat_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'robot-004',
    name: 'WR-004 Zephyr',
    serial_number: 'WR2024-004-ZEP',
    warehouse_id: 'wh-001',
    status: 'CHARGING',
    battery_percent: 15,
    coord_x: 0,
    coord_y: 0,
    last_heartbeat_at: new Date(Date.now() - 1000 * 30).toISOString(),
  },
];

// ─── Mock Bins (20 bins in grid) ─────────────────────────────────────────────
export const MOCK_BINS: Bin[] = Array.from({ length: 20 }, (_, i) => {
  const zone = i < 8 ? 'zone-A' : i < 16 ? 'zone-B' : 'zone-C';
  const aisle = `A${Math.floor(i / 4) + 1}`;
  const rack = `R${(i % 4) + 1}`;
  const states: Bin['state'][] = ['VERIFIED', 'VERIFIED', 'VERIFIED', 'MISMATCH', 'MISSING', 'UNKNOWN', 'UNSCANNED'];
  const state = states[i % states.length];
  const skus = ['SKU-ELEC-001', 'SKU-ELEC-002', 'SKU-FURN-001', 'SKU-FURN-002', 'SKU-BOOK-001'];
  const sku = skus[i % skus.length];

  return {
    id: `bin-${String(i + 1).padStart(3, '0')}`,
    code: `${aisle}-${rack}-S${(i % 3) + 1}-B${(i % 2) + 1}`,
    zone_id: zone,
    aisle_id: aisle,
    rack_id: rack,
    shelf_id: `S${(i % 3) + 1}`,
    state,
    expected_sku: sku,
    observed_sku: state === 'MISMATCH' ? 'SKU-WRONG-999' : state === 'MISSING' ? undefined : sku,
    last_scanned_at:
      state !== 'UNSCANNED' ? new Date(Date.now() - 1000 * 60 * (i * 3 + 5)).toISOString() : undefined,
    confidence: state === 'VERIFIED' ? 0.94 + Math.random() * 0.05 : state === 'MISMATCH' ? 0.82 : undefined,
    coord_x: (i % 4) * 10 + 5,
    coord_y: Math.floor(i / 4) * 8 + 4,
  };
});

// ─── Mock KPIs ───────────────────────────────────────────────────────────────
export const MOCK_KPIS: WarehouseKPIs = {
  health_score: 87,
  inventory_accuracy: 99.2,
  mission_success_rate: 94.1,
  robot_uptime: 91.3,
  open_alerts: 7,
  active_missions: 2,
};

// ─── Mock Accuracy Trend (30 days) ───────────────────────────────────────────
export const MOCK_ACCURACY_TREND: AccuracyDataPoint[] = Array.from({ length: 30 }, (_, i) => {
  const date = subDays(new Date(), 29 - i);
  const base = 98.5 + Math.sin(i * 0.4) * 0.8;
  const noise = (Math.random() - 0.5) * 0.4;
  return {
    date: format(date, 'MMM dd'),
    accuracy: Math.min(100, Math.max(97, parseFloat((base + noise).toFixed(1)))),
    alerts: Math.floor(Math.random() * 8 + 2),
  };
});

// ─── Mock Team Members ────────────────────────────────────────────────────────
export const MOCK_TEAM = [
  {
    id: 'tm-001',
    user_id: 'user-004',
    display_name: 'Priya Patel',
    email: 'operator@wareops.dev',
    role: 'WAREHOUSE_OPERATOR' as const,
    status: 'ONLINE' as const,
    last_action: 'Verified bin A1-R2-S3-B1',
    last_action_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    pending_tasks: 4,
    avg_response_time_min: 8,
  },
  {
    id: 'tm-002',
    user_id: 'user-005',
    display_name: 'James Okafor',
    email: 'operator2@wareops.dev',
    role: 'WAREHOUSE_OPERATOR' as const,
    status: 'ONLINE' as const,
    last_action: 'Flagged discrepancy — bin B2-R4-S1-B2',
    last_action_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    pending_tasks: 2,
    avg_response_time_min: 11,
  },
  {
    id: 'tm-003',
    user_id: 'user-006',
    display_name: 'Lin Wei',
    email: 'linwei@wareops.dev',
    role: 'WAREHOUSE_OPERATOR' as const,
    status: 'AWAY' as const,
    last_action: 'Requested rescan — bin C1-R1-S2-B1',
    last_action_at: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    pending_tasks: 6,
    avg_response_time_min: 15,
  },
  {
    id: 'tm-004',
    user_id: 'user-007',
    display_name: 'Diego Morales',
    email: 'dmorales@wareops.dev',
    role: 'WAREHOUSE_OPERATOR' as const,
    status: 'OFFLINE' as const,
    last_action: 'Completed verification queue',
    last_action_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    pending_tasks: 0,
    avg_response_time_min: 7,
  },
];
